CREATE TABLE IF NOT EXISTS `STUDENT` (
`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
`firstName` VARCHAR(26) NOT NULL,
`middleName` VARCHAR(26) NOT NULL,
`lastName` VARCHAR(26) NOT NULL,
`university` VARCHAR(127) NOT NULL,
`specialty` VARCHAR(127) NOT NULL,
`semester` INTEGER(10) NOT NULL,
`entryDate` TIMESTAMP NOT NULL,
`birthDate` TIMESTAMP NOT NULL,
CONSTRAINT fullName UNIQUE (firstName,middleName,lastName)
);
